server:
  port: 8085

spring:
  application:
    name: integral-service
  datasource:
    url: jdbc:mysql://localhost:3306/freezer?useUnicode=true&characterEncoding=utf8
    username: root
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver

rabbitmq:
  queue-integral: integral-queue
  queue-log: log-queue
  exchange: direct.integral
  routing-key-integral: integral
  routing-key-log: log
