server:
  port: 9090

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:8091/user
    goods:
      path: /goods/**
      url: http://localhost:8081/goods
    pay:
      path: /pay/**
      url: http://localhost:8082/pay
    coupon:
      path: /coupon/**
      url: http://localhost:8090/coupon
  sentitiveHeaders:

filter:
  uriList:
    - /pay/
