server:
  port: 8082

spring:
  application:
    name: payment-serviceApi
  datasource:
    url: jdbc:mysql://localhost:3306/freezer?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  dubbo:
    application:
      name: payment-serviceApi
    registry:
      address: zookeeper://localhost:2181
    scan: com.freezer

rabbitmq:
  queue-integral: integral-queue
  queue-log: log-queue
  exchange: direct.integral
  routing-key-integral: integral
  routing-key-log: log
#在启动器里配置忽略
#user:
#  loginTimeout: 10000
