server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/freezer?useUnicode=true&characterEncoding=utf8
    username: root
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: coupon-serviceApi
  dubbo:
    application:
      name: coupon-serviceApi
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      # host: 127.0.0.1
      port: 20883
    scan: com.freezer
#  jackson:
#    default-property-inclusion: non_null
#dubbo:
#  consumer:
#    check: false

