spring:
  datasource:
    url: jdbc:mysql://localhost:3306/freezer?useUnicode=true&characterEncoding=utf8
    username: root
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver

  dubbo:
    application:
      name: user-serviceApi
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      # host: 127.0.0.1
      port: 20882
#  jackson:
#    default-property-inclusion: non_null

server:
  port: 8086
